### PR TITLE
Add hash table for faster node lookups

### PR DESCRIPTION
**Pull request by philipaconrad**
This PR adds a hash table for speeding up node lookups by ID. Nodes are added to the table at node creation time, and are currently never deleted.

### CODE REVIEW

**Comment by philipaconrad** [comment]
Valgrind says we've got some bytes lost, so I'll go dig into that to make sure I didn't introduce any memory leaks.

**Comment by philipaconrad** [comment]
Okay, after chatting with @charlesdaniels, it seems the valgrind `definitely lost` bytes are not from this PR.

**Comment by charlesdaniels** [comment]
Looks good, go ahead and squash merge when you are ready.

**Comment by philipaconrad** [comment]
Closes issue #5

**Pull request merged**
